development:
  sessions:
    default:
      database: cigarettes_development
      hosts:
        - localhost:27017
  options:
test:
  sessions:
    default:
      database: cigarettes_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
      options:
production:
  sessions:
    default:
      uri: mongodb://heroku_98brsjlv:g4669t8ed157atckbh4binbjm5@ds035004.mongolab.com:35004/heroku_98brsjlv
      options:
        max_retries: 30
        retry_interval: 1
        timeout: 15
        refresh_interval: 10
